# Generated by Django 5.1.4 on 2025-01-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
