# Generated by Django 5.1.4 on 2025-01-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceproduct',
            name='price',
        ),
    ]
