# Generated by Django 5.1.4 on 2025-01-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_invoiceproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
